services:
  - type: web
    name: projectvault
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: DIGEST_FROM_EMAIL
        sync: false
